{{- if .Values.productionIngress -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "studio.fullname" . }}-production
  labels:
    app: {{ template "studio.fullname" . }}
    tier: ingress
    type: production
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    ingressClassName: "nginx"
spec:
  rules:
    - host: {{.Release.Name}}.studio.learningequality.org
      http:
        paths:
        - backend:
            serviceName: {{ template "studio.fullname" . }}-app
            servicePort: 80
{{- end }}
