apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}
  labels:
    app: studio
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postmark-api-key: {{ .Values.studioApp.postmarkApiKey | default "" | b64enc }}
  redis-password: {{ .Values.redis.password | default "" | b64enc }}
  postgres-user: {{ index .Values "cloudsql-proxy" "credentials" "username" | b64enc }}
  postgres-password: {{ index .Values "cloudsql-proxy" "credentials" "password" | b64enc }}
  postgres-database: {{ index .Values "cloudsql-proxy" "credentials" "dbname" | b64enc }}
  sentry-dsn-key: {{ .Values.sentry.dsnKey | b64enc }}
  gcs-writer-service-account-key: {{ .Values.studioApp.gcs.writerServiceAccountKeyBase64Encoded }}
